#!/usr/bin/env bash
# Run both methods on every package that has a *.truth.txt and print a
# precision / recall / F1 summary table.
set -euo pipefail

cd "$(dirname "$0")"

packages=()
for truth in results/*.truth.txt; do
    [ -e "$truth" ] || continue
    name=$(basename "$truth" .truth.txt)
    packages+=("$name")
done

if [ "${#packages[@]}" -eq 0 ]; then
    echo "no ground-truth files found in results/" >&2
    exit 1
fi

# Build one matlab invocation that processes everything.
mcall=""
for p in "${packages[@]}"; do
    mcall+="auto_add_paths('packages/$p','results/$p.matlab.txt'); "
done
echo "== running matlab script on ${#packages[@]} package(s) =="
matlab -batch "addpath(pwd); $mcall" > /dev/null 2>&1 || {
    echo "matlab run failed" >&2; exit 1;
}

scoreboard=SCOREBOARD.md
{
    printf "# Scoreboard\n\n"
    printf "Generated by \`run_all.sh\` on %s.\n\n" "$(date -u +'%Y-%m-%d %H:%M UTC')"
    printf "| package | matlab P | matlab R | matlab F1 | ai P | ai R | ai F1 |\n"
    printf "|---------|---------:|---------:|----------:|-----:|-----:|------:|\n"
} > "$scoreboard"

printf "\n%-18s %-10s %-10s %-10s %-10s\n" "package" "method" "precision" "recall" "F1"
printf -- "-----------------------------------------------------------\n"

score_one() {
    local name="$1" method="$2"
    local cand="results/${name}.${method}.txt"
    if [ ! -f "$cand" ]; then
        echo "N/A N/A N/A"
        return
    fi
    local out
    out=$(./eval.sh "results/${name}.truth.txt" "$cand" | tail -4)
    local p r f
    p=$(echo "$out" | awk '/precision/ {print $3}')
    r=$(echo "$out" | awk '/recall/    {print $3}')
    f=$(echo "$out" | awk '/F1/        {print $3}')
    echo "$p $r $f"
}

for p in "${packages[@]}"; do
    read mp mr mf <<< "$(score_one "$p" matlab)"
    read ap ar af <<< "$(score_one "$p" ai)"
    printf "%-18s %-10s %-10s %-10s %-10s\n" "$p" "matlab" "$mp" "$mr" "$mf"
    printf "%-18s %-10s %-10s %-10s %-10s\n" "$p" "ai"     "$ap" "$ar" "$af"
    printf "| %s | %s | %s | %s | %s | %s | %s |\n" \
        "$p" "$mp" "$mr" "$mf" "$ap" "$ar" "$af" >> "$scoreboard"
done

echo
echo "scoreboard written to $scoreboard"
